receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      memory:

processors:
  batch:
    timeout: 10s

exporters:
  otlphttp/openobserver:
    endpoint: "http://openobserve:5080/api/default"
    headers:
      Authorization: Basic cm9vdEBleGFtcGxlLmNvbTpDb21wbGV4cGFzcyMxMjM=
      stream-name: default
  debug:

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserver, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserver, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserver, debug]
